service: linkedin-professional
frameworkVersion: '2'

custom:
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: us-east-1
  environment:
    LINKEDIN_ACCESS_TOKEN: ${ssm:devopstar-linkedin-access-token}
    LINKEDIN_PROFILE_ID: ${ssm:devopstar-linkedin-profile-id}
    DEEP_AI_TOKEN: ${ssm:devopstar-deep-ai-token}
    ENABLE_LINKEDIN_POSTS: "False"

functions:
  skills:
    handler: handler.skills
    events:
      - http:
          path: skills
          method: get
  share:
    handler: handler.share
    events:
      - schedule: rate(24 hours)

plugins:
  - serverless-python-requirements
