service: linkedin-professional
frameworkVersion: '2'

custom:
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: us-east-1
  environment:
    LINKEDIN_CLIENT_ID: ${ssm:devopstar-linkedin-client-id}
    LINKEDIN_CLIENT_SECRET: ${ssm:devopstar-linkedin-client-secret}
    LINKEDIN_ACCESS_TOKEN: ${ssm:devopstar-linkedin-access-token}
    DEEP_AI_TOKEN: ${ssm:devopstar-deep-ai-token}

functions:
  skills:
    handler: handler.skills
    events:
      - http:
          path: skills
          method: get

plugins:
  - serverless-python-requirements
